### ISSUE TITLE
PUT device state not working

### ISSUE THREAD

**Issue by fannysoderlund** [homedork-se2/Mocked-client#18]
There is an issue when trying to change the device state. In the HttpRequest code there is a POST method, but in the http file there is a PUT URL. It doesn't work to change the state of a device

**Comment by Willz01** [comment]
looks kinda strange because devices/001 URI should return just the edited (PUT) JSON object: `{id, name, state}` instead of the **" List "** it returns.
/devices URI should return a JSON array, instead of {}. So I guess the issue might be linked to returning a list wrapped object.
Maybe look at the request/response mapping in postman. @szomer

**Comment by fannysoderlund** [comment]
Not relative to our mock environment
